on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: tests

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        rust:
          - 1.87 # stable release as of 2025-05-17
          - 1.46.0  # MSRV

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        name: Setup rust toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        name: Load dependencies from cache

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test

      - name: Integration tests
        run: |
          cd integration_tests
          cargo test -- --format=pretty --nocapture

      - uses: actions-rs/cargo@v1
        name: Check for non-standard formatting
        if: ${{ matrix.rust == 'stable' }}
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Check for clippy hints
        with:
          command: clippy
          args: -- -D warnings
